SocialAnalyticsProject/SocialAnalyticsProject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
        url(r'^accounts/', include('allauth.urls')),
    path('',include('reporting.urls'))
]

SocialAnalyticsProject/reporting/urls.py
from django.urls import path
from django.conf.urls import url

from . import views
app_name = "reporting"

urlpatterns = [
    path('',views.login_page,name='login_page'),
    path('login/',views.login_page,name='login_page'),
    path('report/',views.get_insight,name='report'),
    path('pages/<int:page_pk>/engagement/<str:date_preset>',views.get_engagement,name='engagement'),
    path('pages/<int:page_pk>/growth/1day_monthly',views.get_1day_monthly_growth,name='this_month_vas_last_month_growth'),
    path('pages/<int:page_pk>/growth/1week_monthly',views.get_1week_monthly_growth,name='this_month_vas_last_month_growth'),
    path('pages/<int:page_pk>/growth/28days_monthly',views.get_28days_monthly_growth,name='this_month_vas_last_month_growth'),
    path('pages/<int:page_pk>/growth/1day_daily',views.get_1day_daily_growth,name='today_vs_yesterday_growth'),
    path('growth/page/<int:page_pk>', views.growth_page, name='growth_page'),
    path('growth/', views.growth_default_page, name='growth_default_page'),
    path('news/category/<str:category>', views.get_top_headlines_category, name='get_top_headlines_category'),
    path('news/q/<str:keyword>', views.get_top_headlines_keyword, name='get_top_headlines_keyword'),
    path('news/', views.news_suggestions, name='news_suggestions'),
    path('news/keyword', views.news_suggestions_keyword, name='news_suggestions_keyword'),
    path('post/<int:post_id>/predict/',views.get_post_sentiment, name= 'get_post_sentiment'),
    path('post/<int:post_id>/sync_comments/',views.sync_comments, name= 'sync_comments'),
    path('prediction/', views.predict_page, name='predict_page'),
    path('post/<int:post_id>/sentiments/', views.sentiments_page, name='sentiments_page'),
    path('related-topics/<str:topic>',views.get_related_topics, name= 'get_related_topics'),
    path('collect-comments/',views.collect_comments_page, name= 'collect_comments_page'),
    path('change-fav-page/',views.change_fav_page, name= 'change-fav-page'),
]

SocialAnalyticsProject/reporting/models.py
from django.db import models
from landing.models import *
from django.contrib.postgres.fields import JSONField
from django.db import models
from django.contrib.auth.models import User
from allauth.socialaccount.models import SocialAccount


class FacebookPage(models.Model):
    page_id = models.CharField(max_length=2048,unique=True)
    account = models.ForeignKey(SocialAccount,on_delete=models.CASCADE,related_name='user_pages')
    access_token = models.CharField(max_length=2048)
    name = models.CharField(max_length=248)

    def __str__(self):
        return self.name


class FacebookPost(models.Model):

    created_time = models.DateTimeField()
    content = models.CharField(max_length=2048)
    link = models.CharField(max_length=2048, null=True)
    week_day = models.IntegerField(null=True)
    hour = models.IntegerField(null=True)
    post_type = models.IntegerField(null=True)
    post_id = models.CharField(max_length=2048, unique=True)
    comments_synced = models.BooleanField(default=False)
    nb_comments = models.IntegerField(default=0)
    page = models.ForeignKey(FacebookPage, on_delete=models.CASCADE)


class FacebookComment(models.Model):

    created_time = models.DateTimeField()
    content = models.CharField(max_length=2048)
    comment_id = models.CharField(max_length=2048, unique=True)
    post = models.ForeignKey(FacebookPost, on_delete=models.CASCADE)


class InstagramPost(models.Model):
    content = models.CharField(max_length=2048)
    date = models.DateField()


class InstagramReport(models.Model):
    impressions = models.IntegerField()
    engagement = models.IntegerField()
    date = models.DateField()
    post = models.ForeignKey(InstagramPost, on_delete=models.CASCADE)


class FacebookPostReport(models.Model):
    reactions = models.IntegerField(default=0)
    reach = models.IntegerField(default=0)
    impressions = models.IntegerField()
    engagement = models.IntegerField()
    sentiment = JSONField(null=True)
    date = models.DateField()
    post = models.OneToOneField(FacebookPost, on_delete=models.CASCADE)


class FacebookPageReport(models.Model):
    impressions = models.IntegerField()
    engagement = models.IntegerField()
    date = models.DateField()
    page = models.ForeignKey(FacebookPage, on_delete=models.CASCADE)


class UserPreferences(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    business_category = models.CharField(max_length=128, null=True)
    fav_page = models.ForeignKey(
        FacebookPage, on_delete=models.CASCADE, null=True)

SocialAnalyticsProject/reporting/views.py
from django.shortcuts import render, redirect, reverse
from allauth.socialaccount.models import SocialToken
import requests
from modules.schedules.tasks import *
from modules.facebook_api.tasks import engagement_growth_task, page_engagement_task
from django.http import JsonResponse
from modules.utils.constants import *
from modules.utils.news import *
from modules.utils.news_v2 import *
from modules.utils.trends import *
from modules.sentiment_analysis.sentiment_urls import predict_multiple_comments
from modules.sentiment_analysis.sentiment_urls import predict_multiple_comments
from modules.utils.facebook_urls import *


from .models import *

def get_user_pages(request):
    user_pages = FacebookPage.objects.filter(account__user=request.user)
    return user_pages

def get_insight(request):
    #user = request.user
    #
    #token = SocialToken.objects.get(account__user = user)
    #
    #url = "https://graph.facebook.com/v6.0/me/accounts"
    #
    #PARAMS = {'access_token':token}
    # r = requests.get(url = url, params = PARAMS)
    # extracting data in json format
    # data = r.json()
    page_engagement_task.delay(request.user.pk)


def get_engagement(request, page_pk, date_preset):
    t = engagement_growth_task.delay(
        page_pk, METRIC_POST_ENGAGEMENTS, date_preset)
    result = t.wait(timeout=None, interval=0.5)
    return JsonResponse(data=result, safe=False)

# Compares the engagement of the past 28 days with the engagement on the same period last month


def get_28days_monthly_growth(request, page_pk):
    t = engagement_growth_task.delay(
        page_pk, METRIC_POST_ENGAGEMENTS, 'this_month')
    this_month = t.wait(timeout=None, interval=0.5)
    t = engagement_growth_task.delay(
        page_pk, METRIC_POST_ENGAGEMENTS, 'last_month')
    last_month = t.wait(timeout=None, interval=0.5)
    this_month_value = this_month['data'][2]['values'][0]['value']
    last_month_value = last_month['data'][2]['values'][0]['value']
    growth = this_month_value - last_month_value
    if growth>0:
        growth_str = "+" + str(growth)
        ratio = "+" + str(((this_month_value/last_month_value) * 100) - 100)
    else:
        growth_str = str(growth)
        ratio = "-" + str(((last_month_value/this_month_value) * 100) - 100)

    result = {
        "growth": growth_str,
        "current": this_month_value,
        "last": last_month_value,
        "ratio": ratio,
    }
    return JsonResponse(data=result, safe=False)

# Compares the engagement of this week with the engagement on the same week last month


def get_1week_monthly_growth(request, page_pk):
    t = engagement_growth_task.delay(
        page_pk, METRIC_POST_ENGAGEMENTS, 'this_month')
    this_month = t.wait(timeout=None, interval=0.5)
    t = engagement_growth_task.delay(
        page_pk, METRIC_POST_ENGAGEMENTS, 'last_month')
    last_month = t.wait(timeout=None, interval=0.5)
    this_month_value = this_month['data'][1]['values'][0]['value']
    last_month_value = last_month['data'][1]['values'][0]['value']
    growth = this_month_value - last_month_value
    if growth>0:
        growth_str = "+" + str(growth)
        ratio = "+" + str(((this_month_value/last_month_value) * 100) - 100)
    else:
        growth_str = str(growth)
        ratio = "-" + str(((last_month_value/this_month_value) * 100) - 100)

    result = {
        "growth": growth_str,
        "current": this_month_value,
        "last": last_month_value,
        "ratio": ratio,
    }
    return JsonResponse(data=result, safe=False)

# Compares the engagement of today with the engagement on the same day last month


def get_1day_monthly_growth(request, page_pk):
    t = engagement_growth_task.delay(
        page_pk, METRIC_POST_ENGAGEMENTS, 'this_month')
    this_month = t.wait(timeout=None, interval=0.5)
    t = engagement_growth_task.delay(
        page_pk, METRIC_POST_ENGAGEMENTS, 'last_month')
    last_month = t.wait(timeout=None, interval=0.5)
    this_month_value = this_month['data'][0]['values'][0]['value']
    last_month_value = last_month['data'][0]['values'][0]['value']
    growth = this_month_value - last_month_value
    if growth>0:
        growth_str = "+" + str(growth)
        ratio = "+" + str(((this_month_value/last_month_value) * 100) - 100)
    else:
        growth_str = str(growth)
        ratio = "-" + str(((last_month_value/this_month_value) * 100) - 100)

    result = {
        "growth": growth_str,
        "current": this_month_value,
        "last": last_month_value,
        "ratio": ratio,
    }
    return JsonResponse(data=result, safe=False)

# Compares the engagement of today with the engagement of yesterday


def get_1day_daily_growth(request, page_pk):
    t = engagement_growth_task.delay(page_pk, METRIC_POST_ENGAGEMENTS, 'today')
    today = t.wait(timeout=None, interval=0.5)
    t = engagement_growth_task.delay(
        page_pk, METRIC_POST_ENGAGEMENTS, 'yesterday')
    yesterday = t.wait(timeout=None, interval=0.5)
    today_value = today['data'][0]['values'][0]['value']
    yesterday_value = yesterday['data'][0]['values'][0]['value']
    growth = today_value - yesterday_value
    if growth>0:
        growth_str = "+" + str(growth)
        ratio = "+" + str(((today_value/yesterday_value) * 100) - 100)
    else:
        growth_str = str(growth)
        ratio = "-" + str(((yesterday_value/today_value) * 100) - 100)

    result = {
        "growth": growth_str,
        "current": today_value,
        "last": yesterday_value,
        "ratio": ratio,
    }
    return JsonResponse(data=result, safe=False)

def get_top_headlines_category(request, category):
    data = top_headlines_category(category)
    result = data['articles']
    return JsonResponse(data=result, safe=False)

def get_top_headlines_keyword(request, keyword):
    data = top_headlines_keyword_v2(keyword)
    result = data['articles']
    return JsonResponse(data=result, safe=False)

def get_related_topics(request, topic):
    data = get_related_trending_topics(topic)
    # result = data[topic]['rising']['topic_title']
    result = data[topic]['top']['topic_title'].to_dict()
    return JsonResponse(data=result, safe=False)

def get_post_sentiment(request, post_id):

    return JsonResponse(data=data, safe=False)


def news_suggestions(request):
    context = {
        'title': 'News Suggestion',
        'user_pages': get_user_pages(request),
    }
    return render(request, 'news.html', context)


def news_suggestions_keyword(request):
    context = {
        'title': 'News Suggestion Keyword',
        'user_pages': get_user_pages(request),
    }
    return render(request, 'keyword_news.html', context)

def growth_choose_page(request):
    context = {
        'title': 'Growth - Choose a page',
        'user_pages': get_user_pages(request),
    }
    return render(request, 'growth_choose.html', context)
    
def growth_page(request, page_pk):
    context = {
        'title': 'Growth',
        'page_pk': page_pk,
        'user_pages': get_user_pages(request),
    }
    return render(request, 'growth.html', context)
        
def predict_page(request):
    context = {
        'title': 'Post Prediction',
        'user_pages': get_user_pages(request),
    }
    return render(request, 'predict.html', context)

def sentiments_page(request,post_id):
    post = FacebookPost.objects.get(pk=post_id,page__account__user=request.user)

    post_report = FacebookPostReport.objects.get(post=post)

    if post_report.sentiment == None:

        facebook_comment_list = list(FacebookComment.objects.filter(
            post=post).values_list('content', flat=True))

        data = predict_multiple_comments(facebook_comment_list)

        post_report.sentiment = data
        post_report.save()

    else:
        data = post_report.sentiment

    context = {
        'title': 'Sentiment Analysis',
        "data": data,
        'user_pages': get_user_pages(request),
    }
    return render(request, 'sentiment.html', context)

def collect_comments_page(request):
    try:
        user_prefs = UserPreferences.objects.get(user=request.user)
    except:
        # We take the first page in case there is no user prefs
        page = FacebookPage.objects.filter(account__user=request.user).first()
        user_prefs = UserPreferences(
            user=request.user,
            fav_page=page,
            business_category='',
            )
        user_prefs.save()
    page = user_prefs.fav_page
    posts = FacebookPost.objects.filter(page=page).order_by('-pk')
    context = {
        'title': 'Comments Collect',
        'page': page,
        'posts': posts,
        'user_pages': get_user_pages(request),
    }
    return render(request, 'posts_collect_comments.html', context)

def sync_comments(request,post_id):
    post = FacebookPost.objects.get(pk=post_id,page__account__user=request.user)
    
    if not post.comments_synced:
        
        data_comments = get_comments(post.post_id,post.page.access_token)

        for comment in data_comments['data']:
            facebook_comment = FacebookComment.objects.create(content=comment['message'],comment_id=comment['id'],post=post,created_time=datetime.datetime.now())
            facebook_comment.save()

        post.nb_comments = len(data_comments['data'])
        post.comments_synced = True

        post.save()

    return redirect(reverse('reporting:collect_comments_page'))

def growth_default_page(request):
    try:
        user_prefs = UserPreferences.objects.get(user=request.user)
    except:
        # We take the first page in case there is no user prefs
        page = FacebookPage.objects.filter(account__user=request.user).first()
        user_prefs = UserPreferences(
            user=request.user,
            fav_page=page,
            business_category='',
            )
        user_prefs.save()
    page = user_prefs.fav_page
    context = {
        'title': 'Growth',
        'page_pk': page.pk,
        'user_pages': get_user_pages(request),
    }

SocialAnalyticsProject/reporting/templates/growth.html
{% extends 'base.html' %}
{% load static %}
    {% block content %}

        <div class="row">
          <div class="col-md-12 grid-margin stretch-card">
            <h2></h2>
          </div>
        </div>
        <div class="row">
            <div class="col-md-6 stretch-card grid-margin">
              <div class="card bg-gradient-danger card-img-holder text-white">
                <div class="card-body">
                  <h4 class="font-weight-normal mb-3">28 Days Monthly Engagement Growth <i class="mdi mdi-chart-line mdi-24px float-right"></i>
                  </h4>
                  <h2 id="m28d" class="mb-5"></h2>
                  <h6 class="card-text">Growth: <span id="m28d-ratio"></span>%</h6>
                </div>
              </div>
            </div>
            <div class="col-md-6 stretch-card grid-margin">
              <div class="card bg-gradient-info card-img-holder text-white">
                <div class="card-body">
                  <h4 class="font-weight-normal mb-3">7 Days Monthly Engagement Growth <i class="mdi mdi-chart-line mdi-24px float-right"></i>
                  </h4>
                  <h2 id="m7d" class="mb-5"></h2>
                  <h6 class="card-text">Growth: <span id="m7d-ratio"></span>%</h6>
                </div>
              </div>
            </div>
            <div class="col-md-6 stretch-card grid-margin">
              <div class="card bg-gradient-success card-img-holder text-white">
                <div class="card-body">
                  <h4 class="font-weight-normal mb-3">1 Day Monthly Engagement Growth <i class="mdi mdi-chart-line mdi-24px float-right"></i>
                  </h4>
                  <h2 id="m1d" class="mb-5"></h2>
                  <h6 class="card-text">Growth: <span id="m1d-ratio"></span>%</h6>
                </div>
              </div>
            </div>
            <div class="col-md-6 stretch-card grid-margin">
              <div class="card bg-gradient-dark card-img-holder text-white">
                <div class="card-body">
                  <h4 class="font-weight-normal mb-3">Daily Engagement Growth <i class="mdi mdi-chart-line mdi-24px float-right"></i>
                  </h4>
                  <h2 id="d1d" class="mb-5"></h2>
                  <h6 class="card-text">Growth: <span id="d1d-ratio"></span>%</h6>
                </div>
              </div>
            </div>
          </div>
    {% endblock %}

    {% block scripts %}
    <script>
        function showGrowth(page_id) {
            var result = null;
            $.get( "/pages/" + page_id + "/growth/1day_monthly", function( data ) {
                result = data;
                console.log(result);
                $('#m1d').html(result.current + ' (' + result.growth + ')')
                $('#m1d-ratio').html(result.ratio)
            });
            
            var result = null;
            $.get( "/pages/" + page_id + "/growth/1week_monthly", function( data ) {
                result = data;
                console.log(result);
                $('#m7d').html(result.current + ' (' + result.growth + ')')
                $('#m7d-ratio').html(result.ratio)
            });
            
            var result = null;
            $.get( "/pages/" + page_id + "/growth/28days_monthly", function( data ) {
                result = data;
                console.log(result);
                $('#m28d').html(result.current + ' (' + result.growth + ')')
                $('#m28d-ratio').html(result.ratio)
            });
            
            var result = null;
            $.get( "/pages/" + page_id + "/growth/1day_daily", function( data ) {
                result = data;
                console.log(result);
                $('#d1d').html(result.current + ' (' + result.growth + ')')
                $('#d1d-ratio').html(result.ratio)
            });
        }
        
        showGrowth({{page_pk}});
    </script>
    {% endblock %}

SocialAnalyticsProject/reporting/templates/growth_choose.html
{% extends 'base.html' %}
{% load static %}
    {% block content %}

        <div class="row">
          <div class="col-md-12 grid-margin stretch-card">
            <h2>Choose a page to check the growth of</h2>
          </div>
        </div>
        
    {% endblock %}

    {% block scripts %}
    {% endblock %}

SocialAnalyticsProject/reporting/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Purple Admin</title>
    <!-- plugins:css -->
    <link rel="stylesheet" href="{% static 'assets/vendors/mdi/css/materialdesignicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/vendors/css/vendor.bundle.base.css' %}">
    <!-- endinject -->
    <!-- Plugin css for this page -->
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <!-- endinject -->
    <!-- Layout styles -->
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    <!-- End layout styles -->
    <link rel="shortcut icon" href="{% static 'assets/images/favicon.png' %}" />
  </head>
  <body>
    <div class="container-scroller">
      <div class="container-fluid page-body-wrapper full-page-wrapper">
        <div class="content-wrapper d-flex align-items-center auth">
          <div class="row flex-grow">
            <div class="col-lg-4 mx-auto">
              <div class="auth-form-light text-left p-5">
                <div class="brand-logo">
                  <img src="{% static 'assets/images/logo-elite-mkt.svg' %}">
                </div>
                  <div class="mb-2">
                    <a href="/accounts/facebook/login" type="button" class="btn btn-block btn-facebook auth-form-btn">
                      <i class="mdi mdi-facebook mr-2"></i>Connect using facebook </a>
                  </div>
              </div>
            </div>
          </div>
        </div>
        <!-- content-wrapper ends -->
      </div>
      <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->
    <!-- plugins:js -->
    <script src="{% static 'assets/vendors/js/vendor.bundle.base.js' %}"></script>
    <!-- endinject -->
    <!-- Plugin js for this page -->
    <!-- End plugin js for this page -->
    <!-- inject:js -->
    <script src="{% static 'assets/js/off-canvas.js' %}"></script>
    <script src="{% static 'assets/js/hoverable-collapse.js' %}"></script>
    <script src="{% static 'assets/js/misc.js' %}"></script>
    <!-- endinject -->
  </body>
</html>

SocialAnalyticsProject/reporting/templates/posts_collect_comments.html
{% extends 'base.html' %}
{% load static %}
        {% block content %}
        <div class="row">
            <div class="col-lg-12 grid-margin stretch-card">
              <div class="card">
                <div class="card-body">
                  <h4 class="card-title">Page's posts</h4>
                  {% for p in pages %}
                  <p>{{p}}</p>
                  {% endfor %}
                  <table class="table">
                    <thead>
                      <tr>
                        <th>Date</th>
                        <th>No of comments</th>
                        <th>Content</th>
                        <th>Comments Status</th>
                        <th>Sentiments Analysis Status</th>
                        <th>Action</th>
                      </tr>
                    </thead>
                    <tbody>
                      {% for post in posts %}
                      <tr>
                        <td><a href="#">{{post.created_time|date:"SHORT_DATE_FORMAT"}}</a></td>
                        <td>{{post.nb_comments}}</td>
                        <td>{{ post.content|slice:":20" }}..</td>
                          {% if not post.comments_synced %}

                          <td><label class="badge badge-danger">Comments missing</label></td>
                          <td><label class="badge badge-danger">Not done yet</label></td>
                          <td><a href="{% url 'reporting:sync_comments' post.pk %}">Sync Comments</a></td>

                          {% elif post.facebookpostreport.sentiment == None and post.nb_comments != 0 %}

                          <td><label class="badge badge-success">Synced</label></td>
                          <td><label class="badge badge-danger">Not done yet</label></td>
                          <td><a href="{% url 'reporting:sentiments_page' post.pk %}">Analyze comments</a></td>

                          {% elif post.facebookpostreport.sentiment != None %}

                          <td><label class="badge badge-success">Synced</label></td>
                          <td><label class="badge badge-success">Done</label></td>
                          <td><a href="{% url 'reporting:sentiments_page' post.pk %}">Check results</a></td>
                          
                          {% else %}

                          <td><label class="badge badge-success">Synced</label></td>
                          <td><label class="badge badge-danger">Not done yet</label></td>
                          <td>No comments</td>

                          {% endif %}
                      </tr>
                      {% endfor %}
                     <!--  <tr>
                          <td><a href="#">13/05/2020</a></td>
                          <td>87</td>
                          <td>Today we celebrate the annual anniversary of..</td>
                            <td><label class="badge badge-danger">Comments missing</label></td>
                            <td><label class="badge badge-danger">Not done yet</label></td>
                            <td><a href="#">Sync Comments</a></td>
                        </tr>
                        <tr>
                            <td><a href="#">13/05/2020</a></td>
                            <td>87</td>
                            <td>Today we celebrate the annual anniversary of..</td>
                            <td><label class="badge badge-success">Synced</label></td>
                            <td><label class="badge badge-danger">Not done yet</label></td>
                            <td><a href="#">Analyze comments</a></td>
                        </tr>
                        <tr>
                            <td><a href="#">13/05/2020</a></td>
                            <td>87</td>
                            <td>Today we celebrate the annual anniversary of..</td>
                            <td><label class="badge badge-danger">Comments missing</label></td>
                            <td><label class="badge badge-info">In Progress</label></td>
                            <td><a href="#">Sync Comments</a></td>
                        </tr>
                        <tr>
                            <td><a href="#">13/05/2020</a></td>
                            <td>87</td>
                            <td>Today we celebrate the annual anniversary of..</td>
                            <td><label class="badge badge-success">Synced</label></td>
                            <td><label class="badge badge-success">Done</label></td>
                            <td><a href="#">Check results</a></td>
                        </tr>
                        -->
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
    {% endblock %}
    {% block scripts %}
    {% endblock %}

SocialAnalyticsProject/reporting/templates/predict.html
{% extends 'base.html' %}
{% load static %}
        {% block content %}
        <div class="row">
            <div class="col-md-3 grid-margin stretch-card">
            </div>
            <div class="col-md-6 grid-margin stretch-card">
              <div class="card">
                <div class="card-body">
                  <h4 class="card-title">Prediction form</h4>
                  <p class="card-description"> Fill the required information to estimate the reactions </p>
                  <form class="forms-sample">
                    <div class="form-group">
                      <label for="inputReach">Reach</label>
                      <input type="text" class="form-control" id="inputReach" placeholder="Reach" onchange="updateReactions()">
                    </div>
                    <div class="form-group">
                      <div class="form-group">
                        <label for="inputWeekDay">Week Day</label>
                        <select name="weekday" class="form-control" id="inputWeekDay" onchange="updateReactions()">
                          <option value="1">Sunday</option>
                          <option value="2">Monday</option>
                          <option value="3">Tuesday</option>
                          <option value="4">Wednesday</option>
                          <option value="5">Thursday</option>
                          <option value="6">Friday</option>
                          <option value="7">Saturday</option>
                        </select>
                      </div>
                    </div>
                    <div class="form-group">
                        <label for="inputTime">Time</label>
                        <input type="text" class="form-control" id="inputTime" placeholder="Time" onchange="updateReactions()">
                    </div>
                    <div class="form-group">
                      <div class="form-group">
                        <label for="inputType">Post Type</label>
                        <select class="form-control" id="inputType" onchange="updateReactions()">
                          <option value="1">Picture</option>
                          <option value="2">Link</option>
                        </select>
                      </div>
                    </div>
                  </form>
                </div>
              </div>
            </div>
            <div class="col-md-3 grid-margin stretch-card">
            </div>
        </div>
        <div class="row">
            <div class="col-md-3 grid-margin stretch-card">
            </div>
            <div class="col-md-6 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                      <h4 class="card-title">Prediction</h4>
                      <img src="{% static 'assets/images/fb_reactions.png' %}" class="mb-2 mw-80 w-50 rounded" alt="image">
                      <h1 id="reactions" style="color: #0a8ea0; font-size: 5vw;">? Reactions</h1>
                    </div>
                </div>
            </div>
            <div class="col-md-3 grid-margin stretch-card">
            </div>
        </div>
    {% endblock %}

    {% block scripts %}
    <script>
      function updateReactions() {
        var reach = $('#inputReach').val()
        var reach_coef = 0.031170
        var weekday = $('#inputWeekDay option:selected').val()
        var weekday_coef = -4.077676
        var time = $('#inputTime').val()
        var time_coef = -0.029535
        var typeinput = $('#inputType option:selected').val()
        var type_coef = -0.867579
        var intercept = 97.894934
        var result = intercept + reach * reach_coef + weekday * weekday_coef + time * time_coef + typeinput * type_coef
        result = Math.floor(result)
        $('#reactions').html(result + " Reacions")
      }
    </script>
    {% endblock %}